name: 'Run Unit tests'
description: 'Will run unit tests via QUnit'

runs:
  using: "composite"
  steps:
    - name: Run Unit tests
      shell: bash
      # if [[ $failure == "0" ]]; then exit 1; fi  # on fail command echo failure
      run: |
        echo 'Running unit tests'
        qunit ./tests/qunit
        if [[ $failed > "0" ]];
          then exit 1; # on fail command echo failure
        else
          then exit 0; # on success command echo success
        fi
