name: CI
run-name: Auto Continues Integration for betajs-media-components | Debug Mode ${{ inputs.debug }}

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'demos/**' ]
  pull_request:
    branches: [ '*' ]
    types: [ opened, synchronize, reopened ]
    paths: [ 'src/**', 'tests/**' ]
  workflow_dispatch:
    inputs:
      debug:
        description: 'Will show some additional debug information'
        type: choice
        default: false
        options: [ 'true', 'false' ]
      use-cache:
        description: 'Use cache for the workflow'
        type: choice
        default: false
        options: [ 'true', 'false' ]
  workflow_call:
    inputs:
      appName:
        description: 'Name of the app being deployed'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      commitName:
        description: 'Commit message'
        required: false
        default: ${{ github.event.head_commit.message }}
        type: string
      commitKey:
        description: 'Unique key for cache'
        required: false
        default: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name }} #"${{ github.head_ref }}.${{ github.sha }}"
        type: string
      runsOn:
        description: 'Run on server'
        required: true
        type: string
        default: ubuntu-latest
        # options: [ ubuntu-latest, macos-latest, windows-latest, self-hosted, linux, x64, gpu ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ matrix.node-version }}
      cache-hit: ${{ steps.node.outputs.cache-hit }}
      cache-key: ${{ steps.node.outputs.cache-key }}
      package-cache-dir: ${{ steps.node.outputs.package-cache-dir }}
    defaults:
      run:
        working-directory: .
        shell: bash
    strategy:
      matrix:
        node-version: [ '18.x' ]
        pkg-manager: [ 'npm' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and global packages via npm package manager
        id: node
        uses: ./.github/actions/install-dependencies
        with:
          version: ${{ matrix.node-version }}
          pkg-manager: ${{ matrix.pkg-manager }}
          use-cache: ${{ inputs.use-cache }}

      - name: build component
        uses: ./.github/actions/build-component


  install-chrome:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      chrome-launcher: ${{ steps.chrome-install.outputs.CHROME_INSTALL_PATH }}
    steps:
      - name: Install cheom on Linux
        if: ${{ contains(runner.os, 'Linux') }}
        id: chrome-install
        shell: bash
        run: |
          chmod +x .github/scripts/install-chrome.sh
          .github/scripts/install-chrome.sh
          echo "CHROME_INSTALL_PATH=$(which google-chrome-stable)" >> $GITHUB_ENV

  e2e-tests:
    timeout-minutes: 60
    needs: [ build, install-chrome ]
    continue-on-error: false
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright:v1.44.0-jammy
    strategy:
      matrix:
        project: [ chromium ]
        chrome-version: [ latest ] # latest, stable, beta, dev, canary or number like: 119 or 120.0.6099 (https://googlechromelabs.github.io/chrome-for-testing/)
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and global packages via npm package manager
        id: node
        uses: ./.github/actions/install-dependencies
        with:
          version: '18.x'
          pkg-manager: 'npm'
          use-cache: 'false'

      - name: Run Playwright
        uses: ./.github/actions/playwright-test
        with:
          project: ${{ matrix.project }}
          port: ${{ steps.local-server.outputs.port }}
          chrome-launcher: ${{ needs.install-chrome.outputs.chrome-launcher }}

  unit-tests:
    timeout-minutes: 10
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
        pkg-manager: [ 'npm' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and global packages via npm package manager
        id: node
        uses: ./.github/actions/install-dependencies
        with:
          version: ${{ matrix.node-version }}
          pkg-manager: ${{ matrix.pkg-manager }}
          use-cache: ${{ inputs.use-cache }}

      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests
